name = "PsiTK"
uuid = "d89be4ce-3048-45c0-87f5-cd5ed04aaed3"
version = "1.0.0-DEV"
authors = ["Tobias Sch√§fer"]

[deps]
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
DFTK = "0.7"
LinearAlgebra = "1.12.0"
ProgressMeter = "1.11.0"
YAML = "0.4.16"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
