name = "PsiTK"
uuid = "d89be4ce-3048-45c0-87f5-cd5ed04aaed3"
version = "1.0.0-DEV"
authors = ["Tobias Sch√§fer"]

[deps]
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
